main/urls.py
from django.urls import path, include
from . import views
app_name = "main"
urlpatterns = [
    path('', views.index, name = 'index'),
    path('logout/', views.logoutUser, name='logout'),
    path('opened/', views.openedTasks, name='opened'),
    path('closed/', views.closedTasks, name='closed'),
    path('marks/', views.marksTasks, name='marks'),
    path('payments/', views.payments, name='payments'),
    path('new_task/', views.newTask, name='new_task'),
    path('frozen/', views.frozen, name='frozen'),
    path('setStatus/<str:id>/<str:status_n>', views.setStatus, name='setStatus'),
    path('setInWaitStatus/<str:id>/<status_n>', views.setInWaitStatus, name='setInWaitStatus'),
    path('setPayment/<str:id>/<int:payment_num>/<sum>/<divider>', views.setPayment, name='setPayment'),
    path('payment_page/<payment>', views.paymentPage, name = 'payment_page'),
    path('setPaymentStatus/<payment>/<status>', views.setPaymentStatus, name='setPaymentStatus'),
    path('task/<str:id>', views.taskPage, name='task'),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('welcome/', include('unauth.urls', namespace='unauth')),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User

parts = (('1/2', '50%'),
         ('1/3', '33%'),
         ('1/4', '25%'),
         ('Full', '100%'))

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Исполнитель')
    identified = models.TextField('Идентификатор')
    in_wait_status = models.BooleanField(verbose_name='В ожидании')
    manager = models.TextField('Менеджер')
    short_description = models.TextField(verbose_name='Короткое описание')
    full_description = models.TextField(verbose_name='Полное описание')
    deadline = models.DateField('Дедлайн')
    payment = models.IntegerField('Цена')
    status = models.TextField('Статус')
    documentation_link = models.TextField('Ссылка на методички')
    project_link = models.TextField('Ссылка на проект')
    payment_parts = models.CharField(max_length=50, choices=parts, default='1/2', verbose_name='Части оплаты')
    part1 = models.BooleanField('Первая часть оплачена')
    part2 = models.BooleanField('Вторая часть оплачена')
    part3 = models.BooleanField('Третья часть оплачена')
    part4 = models.BooleanField('Четвёртая часть оплачена')

    def __str__(self):
        return self.identified

    class Meta:
        verbose_name = 'Таск'
        verbose_name_plural = 'Таски'

class payment_mdl(models.Model):
    task_fk = models.ForeignKey(Task, verbose_name='Таск', on_delete=models.CASCADE,)
    payment_id = models.TextField('Идентификатор оплаты')
    summa = models.IntegerField('Сумма')
    payment_date = models.DateField('Дата поступления оплаты')
    paid = models.BooleanField(verbose_name='Оплачено?',default=False)

    def __str__(self):
        return self.payment_id

    class Meta:
        verbose_name = 'Оплата'
        verbose_name_plural = 'Оплаты'

main/forms.py
from django import forms
from .models import Task

class CreateNewTask(forms.ModelForm):
    identified = forms.CharField(label='Идентификатор', widget=forms.TextInput(attrs={'placeholder': 'Идентификатор'}))
    in_wait_status = forms.BooleanField(initial=False, required=False)
    manager = forms.CharField(label='Менеджер', widget=forms.TextInput(attrs={'placeholder': 'Менеджер'}))
    short_description = forms.CharField(label='Короткое описание', widget=forms.Textarea(attrs={'placeholder': 'Короткое описание'}))
    full_description = forms.CharField(label='Полное описание', widget=forms.Textarea(attrs={'placeholder': 'Полное описание'}))
    deadline = forms.DateField(label='Дедлайн', widget=forms.DateInput(attrs={'placeholder': 'Дедлайн'}))
    payment = forms.IntegerField(label='Цена', widget=forms.NumberInput(attrs={'placeholder': 'Цена'}))
    status = forms.CharField(label='Статус', widget=forms.TextInput(attrs={'placeholder': 'Статус'}))
    documentation_link = forms.CharField(label='Ссылка на методички', widget=forms.Textarea(attrs={'placeholder': 'Ссылка на методички'}))
    project_link = forms.CharField(label='Ссылка на проект', widget=forms.Textarea(attrs={'placeholder': 'Ссылка на проект'}))

    class Meta:
        model = Task
        fields = ['user',
                 'identified',
                 'in_wait_status',
                 'manager',
                 'short_description',
                 'full_description',
                 'deadline',
                 'payment',
                 'status',
                 'documentation_link',
                 'project_link',
                 'payment_parts',
                 'part1',
                 'part2',
                 'part3',
                 'part4']

main/views.py
import datetime

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import Task, payment_mdl
from .forms import CreateNewTask
from django import forms
from datetime import date, timedelta, datetime
from django.db.models import Q

days = ['Пн', 'Вт',
        'Ср', 'Чт',
        'Пт', 'Сб',
        'Вс']

months = ['Январь', 'Февраль', 'Март',
          'Апрель', 'Май', 'Июнь',
          'Июль', 'Август', 'Сентябрь',
          'Октябрь', 'Ноябрь', 'Декабрь', ]


# Create your views here.
def index(request):
    if request.user.is_authenticated:
        dates = calendar()
        dates_d = [x.strftime('%d') for x in dates]
        days_d = [days[x.weekday()] for x in dates]
        month = months[int(dates[0].strftime('%m')) - 1]
        tasks = []
        for dt in dates:
            temp_task = []
            temp_task = Task.objects.filter(deadline=dt, status='Активен', in_wait_status=False) | Task.objects.filter(
                deadline=dt, status='Правки', in_wait_status=False)
            temp_str = ''
            if len(temp_task) > 0:
                for t in temp_task:
                    temp_str +=  str(t.identified) + ', '
            tasks.append(temp_str)
        context = {'dates': dates_d, 'days': days_d, 'month': month, 'tasks': tasks}
        return render(request, 'main/index.html', context)
    else:
        return redirect('unauth:w_home')


def logoutUser(request):
    logout(request)
    return redirect('unauth:w_home')


def openedTasks(request):
    openedTasks_list = Task.objects.filter(status='Активен', in_wait_status=False)
    context = {'list': openedTasks_list}
    return render(request, 'main/opened.html', context)


def marksTasks(request):
    marksTasks_list = Task.objects.filter(status='Правки', in_wait_status=False)
    context = {'list': marksTasks_list}
    return render(request, 'main/marks.html', context)


def frozen(request):
    frozenTasks_list = Task.objects.filter(in_wait_status=True)
    context = {'list': frozenTasks_list}
    return render(request, 'main/wait.html', context)


def closedTasks(request):
    closedTasks_list = Task.objects.filter(status='Закрыт')
    context = {'list': closedTasks_list}
    return render(request, 'main/closed.html', context)


def payments(request):
    payments_list = payment_mdl.objects.all()
    unpaid_list = payment_mdl.objects.filter(paid=False)
    unpaid = 0
    if len(unpaid_list) > 0:
        for el in unpaid_list:
            unpaid += el.summa
    context = {'list': list(reversed(payments_list)), 'unpaid': unpaid}
    return render(request, 'main/payments.html', context)


def newTask(request):
    form = CreateNewTask(initial={'in_wait_status': False})
    if request.method == "POST":
        form = CreateNewTask(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:index')
    context = {'form': form}
    return render(request, 'main/new_task.html', context)


def taskPage(request, id):
    task = Task.objects.filter(identified=id)
    context = {'task': task[0]}
    return render(request, 'main/task_page.html', context)


def setStatus(request, id, status_n):
    Task.objects.filter(identified=id).update(status=status_n)
    task = Task.objects.filter(identified=id)
    context = {'task': task[0]}
    return render(request, 'main/task_page.html', context)


def setInWaitStatus(request, id, status_n):
    Task.objects.filter(identified=id).update(in_wait_status=status_n)
    task = Task.objects.filter(identified=id)
    context = {'task': task[0]}
    return render(request, 'main/task_page.html', context)


def setPayment(request, id, payment_num, sum, divider):
    if payment_num == 1:
        Task.objects.filter(identified=id).update(part1=True)
    elif payment_num == 2:
        Task.objects.filter(identified=id).update(part2=True)
    elif payment_num == 3:
        Task.objects.filter(identified=id).update(part3=True)
    elif payment_num == 4:
        Task.objects.filter(identified=id).update(part4=True)
    task = Task.objects.filter(identified=id)
    context = {'task': task[0]}
    sm = int(sum) / int(divider)
    pay_date = datetime.date.today()
    pid = str(task[0].identified) + ' ' + str(pay_date.strftime('%d.%m.%Y'))
    n_payment = payment_mdl(payment_id=pid, task_fk=task[0], summa=sm, payment_date=pay_date)
    n_payment.save()
    return render(request, 'main/task_page.html', context)


def setPaymentStatus(request, payment, status):
    cr_payment = payment_mdl.objects.filter(payment_id=payment)
    cr_payment.update(paid=status)
    context = {'payment': cr_payment[0]}
    return render(request, 'main/payment_page.html', context)


def paymentPage(request, payment):
    cr_payment = payment_mdl.objects.filter(payment_id=payment)
    context = {'payment': cr_payment[0]}
    calendar()
    return render(request, 'main/payment_page.html', context)


def calendar():
    m = datetime.now().month
    y = datetime.now().year
    ndays = (date(y, m + 1, 1) - date(y, m, 1)).days
    d1 = date(y, m, 1)
    d2 = date(y, m, ndays)
    delta = d2 - d1
    return ([(d1 + timedelta(days=i)) for i in range(delta.days + 1)])

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>

<div>
    <aside>
        <img src="{% static 'main/img/logo_w.png' %}" alt="">
        <span class="logo">Social</span>
        <h4>Навигация</h4>
        <br>
        <ul>

            <a href="{% url 'main:index' %}"><li><i class="fas fa-home"></i> Главная</li></a>
            <a href="{% url 'main:opened' %}"><li><i class="fas fa-lock-open"></i> Открытые</li></a>
            <a href="{% url 'main:marks' %}"><li><i class="fas fa-marker"></i></i> Правки</li></a>
            <a href="{% url 'main:frozen' %}"><li><i class="fas fa-stopwatch"></i> Замороженные</li></a>
            <a href="{% url 'main:closed' %}"><li><i class="fas fa-lock"></i> Закрытые</li></a>
            <a href="{% url 'main:payments' %}"><li><i class="fas fa-coins"></i> Оплаты</li></a>
            <a href="{% url 'main:logout' %}"><li><i class="fas fa-door-open"></i> Выйти</li></a>
        </ul>
    </aside>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</div>
</body>
</html>

main/templates/main/closed.html
{% extends 'main/base.html' %}

{% block title %}
Закрытые
{% endblock %}

{% block content %}
<div class="features">
    <h1>Закрытые заказы</h1>
     {% if list %}
        {% for task in list %}
            <p><a href="{% url 'main:task' task.identified %}"> <i class="fas fa-pen"></i> {{task.identified}}({{task.manager}}) </a></p>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}
Главная
{% endblock %}

{% block content %}
<div class="features">
    <h1>Календарь</h1>
    <table>
        {% if dates %}
        {% if days %}
        {% if tasks %}
        {% if month %}
    <tr>
        <td>{% if dates.0 %} {{dates.0}} ({{days.0}}){% endif %}  {% if tasks.0 %} {{tasks.0|linebreaks}} {% endif %}</td>
                <td>{% if dates.1 %} {{dates.1}} ({{days.1}}){% endif %}   {% if tasks.1 %} {{tasks.1|linebreaks}} {% endif %}</td>
                <td>{% if dates.2 %} {{dates.2}} ({{days.2}}){% endif %}  {% if tasks.2 %} {{tasks.2|linebreaks}} {% endif %}</td>
                <td>{% if dates.3 %} {{dates.3}} ({{days.3}}){% endif %}   {% if tasks.3 %} {{tasks.3|linebreaks}} {% endif %}</td>
                <td>{% if dates.4 %} {{dates.4}} ({{days.4}}){% endif %}   {% if tasks.4 %} {{tasks.4|linebreaks}} {% endif %}</td>
                <td>{% if dates.5 %} {{dates.5}} ({{days.5}}){% endif %}   {% if tasks.5 %} {{tasks.5|linebreaks}} {% endif %}</td>
                <td>{% if dates.6 %} {{dates.6}} ({{days.6}}){% endif %}   {% if tasks.6 %} {{tasks.6|linebreaks}} {% endif %}</td>
    </tr>
        <tr>
                    <td>{% if dates.7 %} {{dates.7}} ({{days.7}}){% endif %}   {% if tasks.7 %} {{tasks.7|linebreaks}} {% endif %}</td>
                    <td>{% if dates.8 %} {{dates.8}} ({{days.8}}){% endif %}   {% if tasks.8 %} {{tasks.8|linebreaks}} {% endif %}</td>
                    <td>{% if dates.9 %} {{dates.9}} ({{days.6}}){% endif %}   {% if tasks.9 %} {{tasks.9|linebreaks}} {% endif %}</td>
                    <td>{% if dates.10 %} {{dates.10}} ({{days.10}}){% endif %}   {% if tasks.10 %} {{tasks.10|linebreaks}} {% endif %}</td>
                    <td>{% if dates.11 %} {{dates.11}} ({{days.11}}){% endif %}   {% if tasks.11 %} {{tasks.11|linebreaks}} {% endif %}</td>
                    <td>{% if dates.12 %} {{dates.12}} ({{days.12}}){% endif %}   {% if tasks.12 %} {{tasks.12|linebreaks}} {% endif %}</td>
                    <td>{% if dates.13 %} {{dates.13}} ({{days.13}}){% endif %}   {% if tasks.13 %} {{tasks.13|linebreaks}} {% endif %}</td>
        </tr>
            <tr>
                        <td>{% if dates.14 %} {{dates.14}} ({{days.14}}){% endif %}   {% if tasks.14 %} {{tasks.14|linebreaks}} {% endif %}</td>
                        <td>{% if dates.15 %} {{dates.15}} ({{days.15}}){% endif %}   {% if tasks.15 %} {{tasks.15|linebreaks}} {% endif %}</td>
                        <td>{% if dates.16 %} {{dates.16}} ({{days.16}}){% endif %}   {% if tasks.16 %} {{tasks.16|linebreaks}} {% endif %}</td>
                        <td>{% if dates.17 %} {{dates.17}} ({{days.17}}){% endif %}   {% if tasks.17 %} {{tasks.17|linebreaks}} {% endif %}</td>
                        <td>{% if dates.18 %} {{dates.18}} ({{days.18}}){% endif %}   {% if tasks.18 %} {{tasks.18|linebreaks}} {% endif %}</td>
                        <td>{% if dates.19 %} {{dates.19}} ({{days.19}}){% endif %}   {% if tasks.19 %} {{tasks.19|linebreaks}} {% endif %}</td>
                        <td>{% if dates.20 %} {{dates.20}} ({{days.20}}){% endif %}   {% if tasks.20 %} {{tasks.20|linebreaks}} {% endif %}</td>
            </tr>
            <tr>
                        <td>{% if dates.21 %} {{dates.21}} ({{days.21}}){% endif %}   {% if tasks.21 %} {{tasks.21|linebreaks}} {% endif %}</td>
                        <td>{% if dates.22 %} {{dates.22}} ({{days.22}}){% endif %}   {% if tasks.22 %} {{tasks.22|linebreaks}} {% endif %}</td>
                        <td>{% if dates.23 %} {{dates.23}} ({{days.23}}){% endif %}   {% if tasks.23 %} {{tasks.23|linebreaks}} {% endif %}</td>
                        <td>{% if dates.24 %} {{dates.24}} ({{days.24}}){% endif %}   {% if tasks.24 %} {{tasks.24|linebreaks}} {% endif %}</td>
                        <td>{% if dates.25 %} {{dates.25}} ({{days.25}}){% endif %}   {% if tasks.25 %} {{tasks.25|linebreaks}} {% endif %}</td>
                        <td>{% if dates.26 %} {{dates.26}} ({{days.26}}){% endif %}   {% if tasks.26 %} {{tasks.26|linebreaks}} {% endif %}</td>
                        <td>{% if dates.27 %} {{dates.27}} ({{days.27}}){% endif %}   {% if tasks.27 %} {{tasks.27|linebreaks}} {% endif %}</td>
            </tr>
            <tr>
                        <td>{% if dates.28 %} {{dates.28}} ({{days.28}}){% endif %}   {% if tasks.28 %} {{tasks.28|linebreaks}} {% endif %}</td>
                        <td>{% if dates.29 %} {{dates.29}} ({{days.29}}){% endif %}   {% if tasks.29 %} {{tasks.29|linebreaks}} {% endif %}</td>
                        <td>{% if dates.30 %} {{dates.30}} ({{days.30}}){% endif %}   {% if tasks.30 %} {{tasks.30|linebreaks}} {% endif %}</td>
                        <td>{% if dates.31 %} {{dates.31}} ({{days.31}}){% endif %}   {% if tasks.31 %} {{tasks.31|linebreaks}} {% endif %}</td>
                        </tr>
    </table>
    {% endif %}
        {% endif %}
        {% endif %}
        {% endif %}
</div>
{% endblock %}

main/templates/main/marks.html
{% extends 'main/base.html' %}

{% block title %}
Правки
{% endblock %}

{% block content %}
<div class="features">
    <h1>Правки по заказам</h1>
     {% if list %}
        {% for task in list %}
            <p><a href="{% url 'main:task' task.identified %}"> <i class="fas fa-pen"></i> {{task.identified}}({{task.manager}}) </a></p>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

main/templates/main/new_task.html
{% extends 'main/base.html' %}

{% block title %}
Новый
{% endblock %}

{% block content %}
<div class="features">
    <h1>Новый заказ</h1>
    <form method="POST" class="new_task_form">
        {% csrf_token %}
        {{form.user}}
        <br>
        {{form.identified}}
        <br>
        {{form.manager}}
        <br>
        {{form.short_description}}
        <br>
        {{form.full_description}}
        <br>
        {{form.deadline}}
        <br>
        {{form.payment}}
        <br>
        {{form.status}}
        <br>
        {{form.documentation_link}}
        <br>
        {{form.project_link}}
        <br>
        {{form.payment_parts}}
        <br>
                <label for="id_part1">Оплачена первая часть</label>
        {{form.part1}}
        <br>
                <label for="id_part2">Оплачена вторая часть</label>
        {{form.part2}}
        <br>
                <label for="id_part3">Оплачена третья часть</label>
        {{form.part3}}
        <br>
                <label for="id_part4">Оплачена четвёртая часть</label>
        {{form.part4}}
        <br>
        <input class="btn btn-warning" type="submit" value="Добавить заказ">
    </form>

</div>
{% endblock %}

main/templates/main/opened.html
{% extends 'main/base.html' %}

{% block title %}
Открытые
{% endblock %}

{% block content %}
<div class="features">
    <h1>Открытые заказы</h1>
    {% if list %}
        {% for task in list %}
            <p><a href="{% url 'main:task' task.identified %}"> <i class="fas fa-pen"></i> {{task.identified}}({{task.manager}}) </a></p>
        {% endfor %}
    {% endif %}
        <a class="btn btn-warning" href="{% url 'main:new_task' %}">Новый таск</a>


</div>
{% endblock %}

main/templates/main/payment_page.html
{% extends 'main/base.html' %}

{% block title %}
Оплата
{% endblock %}

{% block content %}
<div class="features">
    {% if payment %}
    <h1>{{payment.task_fk.identified}} </h1>
        <p>Сумма оплаты: {{payment.summa}}</p>
          {% if payment.paid %}
        <p>Статус оплаты: &#9745</p>
        <a class="btn btn-warning" href="{% url 'main:setPaymentStatus' payment.payment_id False %}">Не оплачено</a>
    {% else %}
    <p>Статус оплаты: &#10008</p>
    <a class="btn btn-warning" href="{% url 'main:setPaymentStatus' payment.payment_id True %}">Оплачено</a>
    {% endif %}
        {% endif %}
</div>
{% endblock %}

main/templates/main/payments.html
{% extends 'main/base.html' %}

{% block title %}
Оплаты
{% endblock %}

{% block content %}
<div class="features">
    <h1>Оплаты</h1>
     {% if unpaid %}
     <p>Ожидаемая сумма оплат: {{unpaid}}</p>
     {% endif %}
     {% if list %}
        {% for payment in list %}
            {% if payment.paid == True %}
            <p><a class="paid" href="{% url 'main:payment_page' payment.payment_id %}"> <i class="fas fa-coins"></i> {{payment}} {{payment.summa}} </a></p>
            {% elif payment.paid == False %}
            <p><a class="unpaid" href="{% url 'main:payment_page' payment.payment_id %}"> <i class="fas fa-coins"></i> {{payment}} ({{payment.summa}} грн) </a></p>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

main/templates/main/task_page.html
{% extends 'main/base.html' %}

{% block title %}
Открытые
{% endblock %}

{% block content %}
<div class="features2">
    {% if task %}
    <h1>{{task.identified}}</h1>
    {% if task.in_wait_status %}
        <a class="btn btn-warning" href="{% url 'main:setInWaitStatus' task.identified False %}">Разморозить</a>
    {% else %}
    <a class="btn btn-warning" href="{% url 'main:setInWaitStatus' task.identified True %}">Заморозить</a>
    {% endif %}

    {% if task.status == 'Активен' %}
        <a class="btn btn-warning" href="{% url 'main:setStatus' task.identified 'Закрыт' %}">Закрыть</a>
        <a class="btn btn-warning" href="{% url 'main:setStatus' task.identified 'Правки' %}">Правки</a>
    {% elif task.status == 'Закрыт'  %}
        <a class="btn btn-warning" href="{% url 'main:setStatus' task.identified 'Активен' %}">Открыть</a>
        <a class="btn btn-warning" href="{% url 'main:setStatus' task.identified 'Правки' %}">Правки</a>
    {% elif task.status == 'Правки'  %}
        <a class="btn btn-warning" href="{% url 'main:setStatus' task.identified 'Активен' %}">Открыть</a>
    {% endif %}






        <p>Дедлайн: {{task.deadline}}</p>
        <p>{{task.short_description}}</p>
        <p>В ожидании: {% if task.in_wait_status %} &#9745 {% else %} &#10008 {% endif %}</p>
        <p>Менеджер: {{task.manager}}</p>

    <p>{{task.full_description|linebreaks}}</p>
    <p>Цена:{{task.payment}}</p>
    <p>Статус:{{task.status}}</p>
    <p><a href="{{task.documentation_link}}">Документация</a></p>
    <p><a href="{{task.project_link}}">Проект</a></p>
    <p>Части оплаты: {{task.payment_parts}}</p>
    {% if task.payment_parts == '1/2' %}
    <p>Первая часть оплачена: {% if task.part1 %} &#9745 {% else %} &#10008 {% endif %}</p>
    <p>Вторая часть оплачена: {% if task.part2 %} &#9745 {% else %} &#10008 {% endif %}</p>
    {% elif task.payment_parts == '1/3' %}
    <p>Первая часть оплачена: {% if task.part1 %} &#9745 {% else %} &#10008 {% endif %}</p>
    <p>Вторая часть оплачена: {% if task.part2 %} &#9745 {% else %} &#10008 {% endif %}</p>
    <p>Третья часть оплачена: {% if task.part3 %} &#9745 {% else %} &#10008 {% endif %}</p>
    {% elif task.payment_parts == '1/4' %}
    <p>Первая часть оплачена: {% if task.part1 %} &#9745 {% else %} &#10008 {% endif %}</p>
    <p>Вторая часть оплачена: {% if task.part2 %} &#9745 {% else %} &#10008 {% endif %}</p>
    <p>Третья часть оплачена: {% if task.part3 %} &#9745 {% else %} &#10008 {% endif %}</p>
    <p>Четвёртая часть оплачена: {% if task.part4 %} &#9745 {% else %} &#10008 {% endif %}</p>
    {% elif task.payment_parts == 'Full' %}
    <p>Оплата: {% if task.part1 %} &#9745 {% else %} &#10008 {% endif %}</p>
    {% endif %}





<hr>

    <p>Блок оплат</p>
    {% if task.payment_parts == '1/2' %}
     {% if task.part1 == False %}
    <a class="btn btn-warning" href="{% url 'main:setPayment' task.identified 1 task.payment 2 %}">Оплачена 1 часть</a>
     {% endif %}
     {% if task.part2 == False %}
    <a class="btn btn-warning" href="{% url 'main:setPayment' task.identified 2  task.payment 2 %}">Оплачена 2 часть</a>
    {% endif %}


    {% elif task.payment_parts == '1/3' %}
     {% if task.part1 == False %}
    <a class="btn btn-warning" href="{% url 'main:setPayment' task.identified 1  task.payment 3 %}">Оплачена 1 часть</a>
     {% endif %}
    {% if task.part2 == False %}
    <a class="btn btn-warning" href="{% url 'main:setPayment' task.identified 2  task.payment 3 %}">Оплачена 2 часть</a>
    {% endif %}
    {% if task.part3 == False %}
    <a class="btn btn-warning" href="{% url 'main:setPayment' task.identified 3  task.payment 3 %}">Оплачена 3 часть</a>
    {% endif %}


    {% elif task.payment_parts == '1/4' %}
      {% if task.part1 == False %}
    <a class="btn btn-warning" href="{% url 'main:setPayment' task.identified 1  task.payment 4 %}">Оплачена 1 часть</a>
     {% endif %}
    {% if task.part2 == False %}
    <a class="btn btn-warning" href="{% url 'main:setPayment' task.identified 2  task.payment 4 %}">Оплачена 2 часть</a>
    {% endif %}
    {% if task.part3 == False %}
    <a class="btn btn-warning" href="{% url 'main:setPayment' task.identified 3  task.payment 4 %}">Оплачена 3 часть</a>
    {% endif %}
     {% if task.part4 == False %}
    <a class="btn btn-warning" href="{% url 'main:setPayment' task.identified 4  task.payment 4 %}">Оплачена 4 часть</a>
    {% endif %}



    {% elif task.payment_parts == 'Full' %}
     {% if task.part1 == False %}
     <a class="btn btn-warning" href="{% url 'main:setPayment' task.identified 1  task.payment 1 %}">Оплачено</a>
     {% endif %}
    {% endif %}

    {% endif %}
</div>
{% endblock %}

main/templates/main/wait.html
{% extends 'main/base.html' %}

{% block title %}
Замороженные
{% endblock %}

{% block content %}
<div class="features">
    <h1>Замороженные заказы</h1>
     {% if list %}
        {% for task in list %}
            <p><a href="{% url 'main:task' task.identified %}"> <i class="fas fa-pen"></i> {{task.identified}}({{task.manager}}) </a></p>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}